spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    show-sql: true
  web:
    locale: en

jwt:
  access-expiration-time-in-minutes: ${ACCESS_EXPIRATION_TIME}
  refresh-expiration-time-in-minutes: ${REFRESH_EXPIRATION_TIME}

user:
  ageLimit: 18